### ISSUE TITLE
Fail when join node to master!

### ISSUE THREAD

**Issue by chithanh89dn** [geerlingguy/ansible-role-kubernetes#32]
HI guys,

I follow this roles to setup and it's done when setup master but when i run kubernetes_roles=node, which have a problem :
"The task includes an option with an undefined variable. The error was: 'kubernetes_join_command' is undefined"
I also check kubernetes_join_command is define in task/main.yml.How can i fix this problem?
Tks so much.

**Comment by Ilshidur** [comment]
Same problem here. Any ideas ?

**Comment by Ilshidur** [comment]
I figured it out.

I was running one playbook per server, which couldn't work because this role must be run on all the servers in just ONE TIME. Reason why is that I was using Terraform and running Ansible with https://github.com/radekg/terraform-provisioner-ansible.

**Comment by pmav99** [comment]
I get the same error, even though I run a single playbook on all the hosts.

**Comment by geerlingguy** [comment]
I have not had this issue, but I'm always running the playbook against at least the master (which is where the command comes from) and one node.

This role currently doesn't work that well if you're running it against individual hosts and not also the master, for the issue you've mentioned in the OP.

**Comment by pmav99** [comment]
OK I think I figured this out. 

The VM template I was using had a swapfile. As a result kubelet was constantly restarting because I had not added `"--fail-swap-on=false"` and consequently https://github.com/geerlingguy/ansible-role-kubernetes/issues/28 was triggered. Due to the silent failure, the play moved on but then `kubernetes_join_command` was never being defined (or perhaps more accurately, `kubeadm token create` never wrote anything to `stdout`; I haven't tested this though).

Perhaps it would be a good idea to add an explicit check for swap but then again you might want to keep this more lightweight.

**Comment by geerlingguy** [comment]
@pmav99 - yeah, in the case of swap I usually use `geerlingguy.swap` to configure it and don't want this role to manage that aspect as well.

**Comment by pmav99** [comment]
Thank you @geerlingguy 
I agree that a kubernetes role should definitely not configure swap. That being said, explicitly checking if `/proc/swaps` has any entries might still make sense

**Comment by geerlingguy** [comment]
For now I'll leave it as is. The kubelet output should always be consulted in the case of a failure to initialize or join nodes, as it usually has the answer pretty clearly logged somewhere (`journalctl -xue kubelet`).
