### ISSUE TITLE
Kubernetes dashboard

### ISSUE THREAD

**Issue by Nacer-BKRM** [geerlingguy/ansible-role-kubernetes#41]
Hi , 

This file is no longer present : 

https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml 

Regards, 

Nacer.

**Comment by kgopi05** [comment]
Hi , 
Use below link for K8s dashboard url. https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml

Regards
Gopi K

**Comment by moikot** [comment]
@kgopi05 The most recent dashboard link should be obtained from [here](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/).
And currently it's https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml 

But kubernetes-metrics-scraper is failing on arm64 (what I do care about) because of https://github.com/kubernetes/dashboard/issues/4029
